name: Sync Subfolders from Another Repository

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  checkout-target:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: '${{ github.repository }}'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'target'

  sync:
    needs: checkout-target
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ['agents/agent_builder', 'agents/agent_functions', 'agents/tool_maker', 'agents/gpts']
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        repository: 'daveshap/OpenAI_Agent_Swarm'
        path: 'source'
    
    - name: Filter out files, merge, and push
      run: |
        pushd source
        FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --subdirectory-filter ${{ matrix.subfolder }} -f -- --all
        rm -rf .git
        popd
        rm -rf target/${{ matrix.subfolder }}
        mkdir -p target/${{ matrix.subfolder }}
        mv -f source/* target/${{ matrix.subfolder }}
        pushd target
        las -lah
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update folder contents from source repository"
        git push
        popd
