name: Sync Subfolders from Another Repository

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target_repo
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: 'daveshap/OpenAI_Agent_Swarm'
          path: source_repo
      - name: Sync Subfolders
        run: |
          search_dirs=("shared" "agents")
          for subfolder in "${search_dirs[@]}"; do
            echo -e "Syncing $subfolder..."
            rm -rfv target_repo/$subfolder || echo "No existing folder to remove" && continue
            mkdir -pv target_repo/$subfolder
            mv -fv source_repo/$subfolder/* target_repo/$subfolder
          done
      - name: Push Changes
        run: |
          cd target_repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update folder contents from source repository"
          git push || echo "No changes to commit, skipping push!"
        
