name: Sync Subfolders from Another Repository

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  checkout-target:
    runs-on: ubuntu-latest
    outputs:
      target-path: ${{ steps.set-target-path.outputs.path }}
    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: '${{ github.repository }}'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'target'

  sync:
    needs: checkout-target
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ['agent_builder', 'agent_functions', 'tool_maker', 'gpts']
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        repository: 'daveshap/OpenAI_Agent_Swarm'
        path: 'source'
    
    - name: Filter out files that are not needed
      run: |
        pushd source
        FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --subdirectory-filter agents/${{ matrix.subfolder }} -f -- --all
        rm -rf .git
        popd

    - name: Replace folder on source with filtered folder
      run: |
        rm -rf target/${{ matrix.subfolder }}
        mv -rf source/* target/${{ matrix.subfolder }}

    - name: Commit and Push Changes
      run: |
        pushd target
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update folder contents from source repository"
        git push
        popd
