name: Sync Subfolders from Another Repository

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ['agents/agent_builder', 'agents/agent_functions', 'agents/tool_maker', 'agents/gpts']
    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: source_repo

    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        repository: 'daveshap/OpenAI_Agent_Swarm'
        path: target_repo
    
    - name: Sync Subfolders
      run: |
        for folder in "${{ matrix.subfolder }}"; do
          mv -fv "source_repo/$folder/" "target_repo/$folder/"
        done
        cd target_repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update folder contents from source repository"
        git push
        
